cat > config.example.toml <<'EOF'
handle = "Benutzername"
port = [5000, 5010]
whoisport = 4000
autoreply = "Abwesend"
imagepath = "~/chat_images"
EOF

echo "config.toml" >> .gitignore
git add config.example.toml .gitignore
git commit -m "Add TOML config template"
git push